# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efcd3819ed7c9f764d864d731c592687eac298842b1d08de1a2dd8be204cff554668de269daea5fc224f85a57c748e6cded8accd57fdf23d771581534a6f2ec0

test:
  secret_key_base: 146e5a4a4f300e504770871a23e07e2615256a566fff777ecd51dadecef7377ef1e45d6aaaacd36fc5c8c90e22439e720d1ef9c09ee88c4ed91c778d1622db32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
